import org.marsik.bugautomation.facts.BugzillaBug;
import org.marsik.bugautomation.facts.BugzillaPriorityLevel;
import org.marsik.bugautomation.facts.TrelloBoard;
import org.marsik.bugautomation.facts.TrelloCard;
import org.marsik.bugautomation.facts.TrelloLabel;
import org.marsik.bugautomation.facts.Bug;
import org.marsik.bugautomation.services.BugzillaActions;
import org.marsik.bugautomation.services.InternalActions;
import org.marsik.bugautomation.services.TrelloActions;
import org.marsik.bugautomation.facts.BugzillaBugFlag;
import org.marsik.bugautomation.services.ConfigurationService;
import org.marsik.bugautomation.stats.SingleStat;
import org.marsik.bugautomation.stats.Stats;

query "getBugInfo" (String bugId)
  $bug: Bug(id str[startsWith] bugId)
  bz: BugzillaBug(bug == $bug)
  card: TrelloCard(bug == $bug || $bug memberOf blocks, $board : board, $status : status, $pos : pos)
  order: Long() from accumulate(
    TrelloCard(this != card, board == $board, $status == status, pos < $pos),
    count(1)
  )
end

query "getCardInfo" (String cardId)
  card: TrelloCard(id == cardId, $board : board, $status : status, $pos : pos)
  order: Long() from accumulate(
    TrelloCard(this != card, board == $board, $status == status, pos < $pos),
    count(1)
  )
end

query "getColumnInfo" (String board, String status)
  card: TrelloCard(board == board, status == status)
end
